package files;

public class payload {
	
	public static String AddUser()
	{
		return "{\r\n"
				+ " \"firstName\": \"Mayur\",\r\n"
				+ " \"lastName\": \"Baghla\",\r\n"
				+ " \"email\": \"mayur-19@gmail.com\",\r\n"
				+ " \"dayOfBirth\": \"1998-06-24\"\r\n"
				+ "}\r\n"
				+ ""; 
	}
	
	public static String DefaultGetResponse()
	{
		return"{\r\n"
				+ "    \"links\": [\r\n"
				+ "        {\r\n"
				+ "            \"rel\": \"self\",\r\n"
				+ "            \"href\": \"http://localhost:8080/api/users\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"rel\": \"profile\",\r\n"
				+ "            \"href\": \"http://localhost:8080/api/profile/users\"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"content\": [\r\n"
				+ "        {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"firstName\": \"Mark\",\r\n"
				+ "            \"lastName\": \"Roach\",\r\n"
				+ "            \"email\": \"workingemail-1@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1939-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/1\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/1\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 2,\r\n"
				+ "            \"firstName\": \"Robert\",\r\n"
				+ "            \"lastName\": \"Doe\",\r\n"
				+ "            \"email\": \"workingemail-2@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1951-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/2\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/2\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 3,\r\n"
				+ "            \"firstName\": \"Mary\",\r\n"
				+ "            \"lastName\": \"Roach\",\r\n"
				+ "            \"email\": \"workingemail-3@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1968-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/3\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/3\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 4,\r\n"
				+ "            \"firstName\": \"John\",\r\n"
				+ "            \"lastName\": \"Li\",\r\n"
				+ "            \"email\": \"workingemail-4@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1986-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/4\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/4\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 5,\r\n"
				+ "            \"firstName\": \"Mary\",\r\n"
				+ "            \"lastName\": \"Doe\",\r\n"
				+ "            \"email\": \"workingemail-5@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1964-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/5\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/5\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 6,\r\n"
				+ "            \"firstName\": \"Alex\",\r\n"
				+ "            \"lastName\": \"Portman\",\r\n"
				+ "            \"email\": \"workingemail-6@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1955-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/6\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/6\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 7,\r\n"
				+ "            \"firstName\": \"Nataly\",\r\n"
				+ "            \"lastName\": \"Portman\",\r\n"
				+ "            \"email\": \"workingemail-7@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1939-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/7\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/7\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 8,\r\n"
				+ "            \"firstName\": \"John\",\r\n"
				+ "            \"lastName\": \"Erickson\",\r\n"
				+ "            \"email\": \"workingemail-8@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1984-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/8\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/8\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 9,\r\n"
				+ "            \"firstName\": \"Robert\",\r\n"
				+ "            \"lastName\": \"Roach\",\r\n"
				+ "            \"email\": \"workingemail-9@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1977-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/9\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/9\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 10,\r\n"
				+ "            \"firstName\": \"Robert\",\r\n"
				+ "            \"lastName\": \"Roach\",\r\n"
				+ "            \"email\": \"workingemail-10@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1980-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/10\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/10\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 11,\r\n"
				+ "            \"firstName\": \"Mary\",\r\n"
				+ "            \"lastName\": \"Smith\",\r\n"
				+ "            \"email\": \"workingemail-11@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1973-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/11\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/11\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 12,\r\n"
				+ "            \"firstName\": \"Mary\",\r\n"
				+ "            \"lastName\": \"Li\",\r\n"
				+ "            \"email\": \"workingemail-12@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1980-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/12\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/12\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 13,\r\n"
				+ "            \"firstName\": \"Nataly\",\r\n"
				+ "            \"lastName\": \"Smith\",\r\n"
				+ "            \"email\": \"workingemail-13@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1994-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/13\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/13\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 14,\r\n"
				+ "            \"firstName\": \"John\",\r\n"
				+ "            \"lastName\": \"Smith\",\r\n"
				+ "            \"email\": \"workingemail-14@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1963-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/14\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/14\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 15,\r\n"
				+ "            \"firstName\": \"John\",\r\n"
				+ "            \"lastName\": \"Li\",\r\n"
				+ "            \"email\": \"workingemail-15@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1996-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/15\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/15\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 16,\r\n"
				+ "            \"firstName\": \"Alex\",\r\n"
				+ "            \"lastName\": \"Portman\",\r\n"
				+ "            \"email\": \"workingemail-16@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1941-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/16\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/16\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 17,\r\n"
				+ "            \"firstName\": \"Nataly\",\r\n"
				+ "            \"lastName\": \"Portman\",\r\n"
				+ "            \"email\": \"workingemail-17@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1959-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/17\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/17\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 18,\r\n"
				+ "            \"firstName\": \"Mary\",\r\n"
				+ "            \"lastName\": \"Doe\",\r\n"
				+ "            \"email\": \"workingemail-18@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1951-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/18\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/18\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 19,\r\n"
				+ "            \"firstName\": \"Robert\",\r\n"
				+ "            \"lastName\": \"Smith\",\r\n"
				+ "            \"email\": \"workingemail-19@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1986-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/19\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/19\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 20,\r\n"
				+ "            \"firstName\": \"Mary\",\r\n"
				+ "            \"lastName\": \"Doe\",\r\n"
				+ "            \"email\": \"workingemail-20@gmail.com\",\r\n"
				+ "            \"dayOfBirth\": \"1968-06-29\",\r\n"
				+ "            \"content\": [],\r\n"
				+ "            \"links\": [\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"self\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/20\"\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"rel\": \"user\",\r\n"
				+ "                    \"href\": \"http://localhost:8080/api/users/20\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"page\": {\r\n"
				+ "        \"size\": 20,\r\n"
				+ "        \"totalElements\": 20,\r\n"
				+ "        \"totalPages\": 1,\r\n"
				+ "        \"number\": 0\r\n"
				+ "    }\r\n"
				+ "}";
	}
}
